#!/bin/bash
#

: ${HOME=~}
: ${LOGNAME=$(id -un)}
: ${UNAME=$(uname)}

: ${HOSTFILE=~/.ssh/known_hosts}
: ${INPUTRC=~/.inputrc}

#---------------------------
# Shell Options
#---------------------------

# System bashrc
test -r /etc/bashrc && . /etc/bashrc

# Notify immedetely
set -o notify

set -o vi

# Shell options
shopt -s cdspell                    # Check cd spelling
shopt -s extglob                    # Extended pattern matching
shopt -s histappend                 # Append history on exit
set +o histexpand
shopt -s hostcomplete               # Attempt to complete '@'
shopt -s interactive_comments       # Allow comments in interactive
shopt -u mailwarn                   # Don't tell me about mail, please.
shopt -s no_empty_cmd_completion    # Don't complete on an empty line.
shopt -s cdable_vars

unset MAILCHECK                     # Don't tell me about mail, please.

#----------------------
# PATH
#----------------------
PATH="$PATH:/usr/local/sbin:/usr/sbin:/sbin"
PATH="/usr/local/bin:$PATH"

test -d "$HOME/devel/bin" && PATH="$HOME/devel/bin:$PATH"

#----------------------
# Environment Config
#----------------------

case "$-" in
    *i*) INTERACTIVE=yes ;;
    *) unset INTERACTIVE ;;
esac

case "$0" in
    -*) LOGIN=yes ;;
    *) unset LOGIN ;;
esac

# Enable UTF locale
: ${LANG:="en_US.UTF-8"}
: ${LANGUAGE:="en"}
: ${LC_CTYPE:="en_US.UTF-8"}
: ${LC_ALL:="en_US.UTF-8"}
export LANG LANGUAGE LC_CTYPE LC_ALL

# Always use passive FTP
: ${FTP_PASSIVE:=1}
export FTP_PASSIVE

# Some filetypes to ignore
FIGNORE="~:CVS:#:.pyc:.swp:.swa"

#HISTORY
export HISTCONTROL="ignoreboth"                 # Ignore space and duplicates 
export HISTSIZE=10000
export HISTFILESIZE=10000
export HISTTIMEFORMAT="[%D%T]"
export HISTIGNORE="fg*:bg*:history*:ls*"
shopt -s cmdhist                                # Save multiline in one line
shopt -s histreedit                             # Reedit failed substitution

#--------------------
# Pager and editor
#--------------------

HAVE_VIM=$(command -v vim)
HAVE_GVIM=$(command -v gvim)

test -n "$HAVE_VIM" && EDITOR=vim || EDITOR=vi
export EDITOR

# PAGER
if test -n "$(command -v less)" ; then
    PAGER="less -FirSwX"
    MANPAGER="less -FiRswX"
else
    PAGER=more
    MANPAGER="$PAGER"
fi
export PAGER MANPAGER

# Ack
ACK_PAGER="$PAGER"
ACK_PAGER_COLOR="$PAGER"

export CLICOLOR="yes"

#-------------------
# LS
#-------------------

LS_COMMON="-hBG"

dircolors="$(type -P gdircolors dircolors | head -1)"
test -n "$dircolors" && {
    COLORS=/etc/DIR_COLORS
    test -e "/etc/DIR_COLORS.$TERM"         && COLORS="/etc/DIR_COLORS.$TERM"
    test -e "$HOME/.dircolors"              && COLORS="$HOME/.dircolors"
    test ! -e "$COLORS"                     && COLORS=
    eval `$dircolors --sh $COLORS`
}
unset dircolors

test -n "$LS_COMMON" &&
    alias ls="command ls $LS_COMMON"

alias ll="ls -l"
alias la="ls -a"
alias l.="ls -d .*"
alias dir="ls"



#----------------------
# Prompt 
#----------------------

RED="\[\033[0;31m\]"
BROWN="\[\033[0;33m\]"
GREY="\[\033[0;97m\]"
BLUE="\[\033[0;34m\]"
PS_CLEAR="\[\033[0m\]"
SCREEN_ESC="\[\033k\033\134\]"

if [ "$LOGNAME" = "root" ]; then
    COLOR1="${RED}"
    COLOR2="${BROWN}"
    P="#"
elif hostname | grep -q 'github\.com'; then
    GITHUB=yep
    COLOR1="\[\e[0;94m\]"
    COLOR2="\[\e[0;92m\]"
    P="\$"
else
    COLOR1="${BLUE}"
    COLOR2="${BROWN}"
    P="\$"
fi

prompt_simple() {
    unset PROMPT_COMMAND
    PS1="[\u@\h:\w]\$ "
    PS2="> "
}

prompt_compact() {
    unset PROMPT_COMMAND
    PS1="${COLOR1}${P}${PS_CLEAR} "
    PS2="> "
}

prompt_color() {
    PS1="${GREY}[${COLOR1}\u${GREY}@${COLOR2}\h${GREY}:${COLOR1}\W${GREY}]${COLOR2}$P${PS_CLEAR} "
    PS2="\[[33;1m\]continue \[[0m[1m\]> "
}

prompt_gitaware() {
    PS1="$(__git_ps1 "(%s)")$ "
    PS2="> "
}

prompt_michael() {
    PS1="[\u@\[\e[32;1m\]\H \[\e[0m\]\w $(__git_ps1 "(%s)")$]\$ " 
}

prompt_noclock() {
    PS1="\[\033[36m\][\t] \[\033[1;33m\]\u\[\033[0m\]@\h:\[\033[36m\][\w]:\[\033[0m\] "
}

#----------------------
# Useful functions
#----------------------

push_ssh_cert() {
    local _host
    test -f ~/.ssh/id_dsa.pub || ssh-keygen -t dsa
    for _host in "$@";
    do
        echo $_host
        ssh $_host 'touch ~/.ssh/authorized_keys'
        ssh $_host 'cat >> ~/.ssh/authorized_keys' < ~/.ssh/id_dsa.pub
    done
}

extract () 
{
    if [ -f $1 ] ; then
        case $1 in
            *.tar.bz2)   tar xvjf $1        ;;
            *.tar.gz)    tar xvzf $1     ;;
            *.bz2)       bunzip2 $1       ;;
            *.rar)       unrar x $1     ;;
            *.gz)        gunzip $1     ;;
            *.tar)       tar xvf $1        ;;
            *.tbz2)      tar xvjf $1      ;;
            *.tgz)       tar xvzf $1       ;;
            *.zip)       unzip $1     ;;
            *.Z)         uncompress $1  ;;
            *.7z)        7z x $1    ;;
            *)           echo "'$1' cannot be extracted via >extract<" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

function ii()   # Get current host related info.
{
    echo -e "\nYou are logged on ${RED}$HOST"
    echo -e "\nAdditionnal information:$NC " ; uname -a
    echo -e "\n${RED}Users logged on:$NC " ; w -h
    echo -e "\n${RED}Current date :$NC " ; date
    echo -e "\n${RED}Machine stats :$NC " ; uptime
}

# -------------------------
# Bash Completion 
# -------------------------
test -z "$BASH_COMPLETION" && {
    bash=${BASH_VERSION%.*}; bmajor=${bash%.*}; bminor=${bash#*.}
    test -n "$PS1" && test $bmajor -gt 1 && {
        # search for a bash_completion file to source
        for f in /usr/local/etc/bash_completion \
            /usr/pkg/etc/bash_completion \
            /opt/local/etc/bash_completion \
            /etc/bash_completion \
            ~/.bash_completion
        do
            test -f $f && {
                . $f
                break
            }
        done
    }
    unset bash bmajor bminor f
}

_expand() {
    return 0
}


#--------------------------
# Mac Specific
#--------------------------

if [ "$UNAME" = Darwin ]; then
    test -x /opt/local -a ! -L /opt/local && {
        PORTS=/opt/local

        PATH="$PORTS/bin:$PORTS/sbin:$PATH"
        MANPATH="$PORTS/share/man:$MANPATH"

        export CPATH=$PORTS/include
        export LIBRARY_PATH=$PORTS/lib
        export LD_LIBRARY_PATH=$PORTS/lib
        export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:$PORTS/lib

    }
fi

# -------------------------
# Closing Notes/User Specific
# -------------------------

# Python interactive shell stuff
PYTHONSTARTUP=~/.pythonrc.py
export PYTHONSTARTUP

test -n "$PS1" && prompt_color

source ~/.rosrc

# Tell me something nifty at login
test -n "$INTERACTIVE" -a -n "$LOGIN" && {
    uname -npsr
    uptime
}
