#!/bin/bash

: ${HOME=~}
: ${LOGNAME=$(id -un)}
: ${UNAME=$(uname)}

: ${HOSTFILE=~/.ssh/known_hosts}
: ${INPUTRC=~/.inputrc}

# System bashrc
test -r /etc/bashrc && . /etc/bashrc

shopt -s nullglob
for file in "$HOME/.bash_profile.d"/*.sh; do
    source "$file"
done
shopt -u nullglob

#----------------------
# Prompt 
#----------------------

ps1_set --prompt ∫ --notime 'S\:\ '

# -------------------------
# Bash Completion 
# -------------------------

if [ -f /etc/bash_completion ] ; then
    . /etc/bash_completion
fi

if [ -f ~/.bash_completion ]; then
    . ~/.bash_completion
fi

# -------------------------
# Closing Notes/User Specific
# -------------------------

source ~/.sshrc
source ~/.rosrc

LD_LIBRARY_PATH=/usr/local/cuda:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH

# Tell me something nifty at login
test -n "$INTERACTIVE" -a -n "$LOGIN" && {
    uname -npsr
    uptime
}
