#!/bin/bash

xrdb -merge .Xresources

xsetroot

eval $(gnome-keyring-daemon)
export GNOME_KEYRING_SOCKET
export GNOME_KEYRING_PID
export SSH_AUTH_SOCK="$GNOME_KEYRING_CONTROL/ssh"

xmodmap -e "remove Lock = Caps_Lock"
xmodmap -e "keysym Caps_Lock = Control_L"
xmodmap -e "add Control = Control_L"

xscreensaver -no-splash &
hamster-time-tracker &
psi &

urxvt -name tasklist -e task shell &

/usr/bin/xmonad
