#!/usr/bin/env python

import sys
import os
import os.path
import argparse

# This is bad.  rospkg doesn't do everything I want, yet
import roslib
import rospkg

import warnings

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    import roslib.rospack


class App(object):
    def __init__(self, args):
        self.args = args

        if self.args.package == '.':
            package = rospkg.get_package_name('.')
        else:
            package = self.args.package

        rp = rospkg.RosPack()

        try:
            pkg_dir = rp.get_path(package)
        except roslib.packages.InvalidROSPkgException:
            print >> sys.stderr, "Could not find package %s" % package
            sys.exit(-1)

        cflags = roslib.rospack.rospackexec(['export',
                                             '--lang=cpp',
                                             '--attrib=cflags',
                                             package])
        flags = set()
        for flag in cflags.split(' '):
            flags.add(flag)

        flags.add("-I${folder:${project_path:manifest.xml}}/cfg/cpp")
        flags.add("-I${folder:${project_path:manifest.xml}}/include")

        flags.add("-Wno-self-assign")
        flags.add("-Wno-delete-non-virtual-dtor")

        self.skeleton = '''{
    "folders":
    [
        {
            "path": "%s"
        }
    ],
    "settings":
    {
        "sublimeclang_options":
        [
            "-Wall",
            %s
        ]
    }
}
''' % (pkg_dir, ',\n            '.join('"%s"' % flag for flag in flags))

        project_name = os.path.join(pkg_dir, package + '.sublime-project')
        print self.skeleton
        print "Writing to " + str(project_name)
        with open(project_name, 'w') as f:
            f.write(self.skeleton)


if __name__ == '__main__':
    try:
        parser = argparse.ArgumentParser()
        parser.add_argument("package")
        args = parser.parse_args()
        App(args)
    except KeyboardInterrupt:
        print >> sys.stderr, "Interrupt caught, exiting"
        sys.exit(-1)
